/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LeaderboardGui;

import WorkoutGui.WorkoutBuddyGui;
import java.awt.Color;
import java.util.ArrayList;

/**
 *
 * @author jamyangtamang
 * Is the frame that keeps the LeaderBoard panels for each exercise
 */
public class LeaderBoardFrame extends javax.swing.JFrame {
    private static WorkoutBuddyGui gui;
    private static LeaderBoardFrame frame;
    private static ArrayList<LeaderBoardPanel> panels;
    
    /**
     * Creates new form LeaderBoardFrame that hosts all LeaderBoardPanels
     * @param gui contains a reference to the the main WorkoutBuddyGui
     *            there can only be one for each user
     * @param frame, is a static instance of itself
     * @param panels, is an array list of pannels, there is one for each exercise
     */
    public LeaderBoardFrame(WorkoutBuddyGui gui){
        initComponents();
        this.setTitle("Leader Boards");
        this.gui = gui;
        this.setBackground(Color.DARK_GRAY);
        panels = new ArrayList();
        LeaderBoardPanel benchpressPanel = new LeaderBoardPanel("BenchPress",this);
        panels.add(benchpressPanel);
        LeaderBoardPanel squatPanel = new LeaderBoardPanel("Squat", this);
        panels.add(squatPanel);
        LeaderBoardPanel deadliftPanel = new LeaderBoardPanel("Deadlift", this);
        panels.add(deadliftPanel);
        jtpEntries.add("BenchPress",benchpressPanel);
        jtpEntries.add("Squat", squatPanel);
        jtpEntries.add("Deadlift", deadliftPanel);
    }

    /**
     * 
     * @param gui the reference to the main WorkoutBuddyGui
     * @return the instance of LeaderBoardFrame, makes a new one if it is null
     */
    public static LeaderBoardFrame getLeaderBoard(WorkoutBuddyGui gui){
        if(frame == null)
            return frame = new LeaderBoardFrame(gui);
        else
            return frame;
    }
    
    /**
     * updates the panels according the the LeaderBoard model
     */
    public static void UpdateFrame(){
        for(int i = 0; i < panels.size(); i++){
            panels.get(i).updateTable();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtpEntries = new javax.swing.JTabbedPane();
        addStats = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        addStats.setText("Add Your Stats");
        addStats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStatsActionPerformed(evt);
            }
        });

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(backBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                        .addComponent(addStats)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jtpEntries)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addStats)
                    .addComponent(backBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtpEntries, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** 
     * modifies the visibility of the frame
     */
    public static void makeVisible(){
        frame.setVisible(true);
    }
    
    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.setVisible(false);
        gui.setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed
    /**
     * Creates a new add stat menu that allow user to enter data
     * @param evt event trigger
     */
    private void addStatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStatsActionPerformed
        AddStats stat = new AddStats(this);
        stat.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_addStatsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addStats;
    private javax.swing.JButton backBtn;
    private javax.swing.JTabbedPane jtpEntries;
    // End of variables declaration//GEN-END:variables
}
