/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LeaderboardGui;

import LeaderBoardModel.LeaderBoardEntry;
import Workout_Web_Services.LeaderBoardDataProvider;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jamyangtamang
 * Is the panel for each exercise in the leaderboard
 * contains a table that shows the leaderboard stats
 */
public class LeaderBoardPanel extends javax.swing.JPanel {
    private final DefaultTableModel model;
    private final Object rowData[] = new Object[3];
    private Thread loadList;
    private static ArrayList<LeaderBoardEntry> leaderBoard;
    private final String exerciseName;
    
    /**
     * Creates new form LoaderBoardPanel
     * @param leaderBoard keeps a reference to the leaderBoard entires for this specific
     *                    panel pertaining to the specific exercise
     */
    public LeaderBoardPanel(String name, LeaderBoardFrame tab) {
        exerciseName = name;
        initComponents();
//        this.setBackground(Color.GRAY);
        model = (DefaultTableModel) leaderBoardTable.getModel();
        getList(exerciseName);
        leaderBoard = LeaderBoardDataProvider.getData(name);
    }
    
    /**
     * builds the table to show stats in ascending order
     * @param exercise 
     */
    private void getList(String exercise){
        model.setRowCount(0);
        leaderBoard = LeaderBoardDataProvider.getData(exercise);
        for(int i = 0; i < leaderBoard.size(); i++){
            rowData[0] = i+1;
            rowData[1] = leaderBoard.get(i).getUserName(); 
            rowData[2] = leaderBoard.get(i).getOneRepMax(); 
            model.addRow(rowData);
        }
    }
    
    /**
     * updates the table based on the leaderBoardStats of the panels exercise
     */
    public void updateTable(){
        leaderBoard.clear();
        getList(exerciseName);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        leaderBoardTable = new javax.swing.JTable();

        leaderBoardTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rank", "User", "1 Rep Max"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(leaderBoardTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable leaderBoardTable;
    // End of variables declaration//GEN-END:variables
}
