/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PlayingExerciseGui;

import LogGui.Log;
import WorkoutGui.WorkoutBuddyGui;
import staticData.DateInfo;
import WorkoutModel.Exercise;
import LogModel.LogModel;
import WorkoutModel.Workout;
/**
 *
 * @author jamyangtamang
 */
public class PlayingExerciseFrame extends javax.swing.JFrame {
    private Workout workout;
    private WorkoutBuddyGui guiComponent;
    
    /**
     * Creates new form PlayExercise
     * @param gui keeps a reference to the WorkoutBuddy
     * @param workout keeps a reference to the workout to which this PlayingExerciseFrame belongs
     */
    public PlayingExerciseFrame(WorkoutBuddyGui gui, Workout workout) {
        initComponents();
        this.setTitle(workout.getName());
        this.guiComponent = gui;
        this.workout = workout;
        for(int i = 0; i < workout.getNumExercise(); i++){
            Exercise exercise = workout.getExercise(i);
            PlayingExercisePanel PlayingPanel = new PlayingExercisePanel(exercise, this);
            jtpExercise.add(exercise.getName(), PlayingPanel);
        }
    }
    
    /**
     * Shifts the tab on the PlayingExerciseFrame
     * If the tab is the last one for this workout it adds an entry to the LogModel
     * marking it as incomplete and brings back the WorkoutGui
     */
    public void nextTab(){
        if(jtpExercise.getSelectedIndex() < jtpExercise.getTabCount()-1)
            jtpExercise.setSelectedIndex(jtpExercise.getSelectedIndex()+1);
        else{
            guiComponent.setVisible(true);
            LogModel.getInstance().addEntry(DateInfo.getDate(), workout.getName(), "Completed");
            Log.getLog(guiComponent).updateLog();
            LogModel.getInstance().saveToLogFile();
            this.dispose();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jtpExercise = new javax.swing.JTabbedPane();
        backBtn = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtpExercise, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backBtn)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(backBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtpExercise, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param evt event trigger
     * Brings back the WorkoutGui and adds an entry to the LogModel marking it as incomplete
     */
    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        guiComponent.setVisible(true);
        LogModel.getInstance().addEntry(DateInfo.getDate(), workout.getName(), "Incomplete");
        Log.getLog(guiComponent).updateLog();
        LogModel.getInstance().saveToLogFile();
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JTabbedPane jtpExercise;
    // End of variables declaration//GEN-END:variables
}
