/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package WorkoutGui;

import WorkoutModel.Exercise;
import WorkoutModel.Workout;

/**
 *
 * @author jamyangtamang
 * Is a subclass of AddExercise  
 * gets a reference to the exercise the user selected and updates it accordingly
 */
public class UpdateExercise extends AddExercise {
    private int updateIndex;
    /**
     * Creates new form UpdateEx
     */
    public UpdateExercise(WorkoutPanel workoutPanel, Workout workoutName, int index) {
        super(workoutPanel, workoutName);
        initComponents();
        this.updateIndex = index;
        this.setTitle("Update Exercise");
    }
    
    /**
     * makes changes to the exercise selected
     */
    public void changeExercises(String name, int set, int rep, double weight, String muscleGroup, String Description, int apiId){
        workout.getExercise(updateIndex).setName(name);
        workout.getExercise(updateIndex).setSet(set);
        workout.getExercise(updateIndex).setRep(rep);
        workout.getExercise(updateIndex).setWeight(weight);
        workout.getExercise(updateIndex).setMuscleGroup(muscleGroup);
        workout.getExercise(updateIndex).setDescription(description);
        workout.getExercise(updateIndex).setapiId(apiId);
    }
    
    /**
     * Overrides the submissionBtnActionPerformed from the super class
     * instead of adding a new entry it just updates the entry for the selected exercise
     */
    @Override
    protected void submissionBtnActionPerformed(java.awt.event.ActionEvent evt) {                                              
        if(checkInputs(numberOfSets.getText(), numberOfReps.getText(), weightInput.getText())){
            name = (String) exerciseName.getSelectedItem();
            muscleGroup = (String) msclGrp.getSelectedItem().toString();
            description = exerciseArray.get(exerciseName.getSelectedIndex()).getDescription();
            apiId = exerciseArray.get(exerciseName.getSelectedIndex()).getapiId();
            changeExercises(name, set, rep, weight, muscleGroup, description, apiId);
            workoutPanel.removeThatRow();
            workoutPanel.updateTable(updateIndex);
            workoutPanel.makeGuiVisible();
            this.dispose();
       }
         
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 439, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 305, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
